version: '3.4'

services:

  logger:
    container_name: cwm-worker-logger
    image: cwm-worker-logger:latest
    build: .
    ports:
      - "8500:8500"
    environment:
      LOG_PROVIDER: default
      # LOG_PROVIDER: elasticsearch
      # LOG_PROVIDER: s3
      LOG_LEVEL: debug
      # CWM_HTTP_HOST: localhost
      # CWM_HTTP_PORT: 8500
      REDIS_HOST: redis
      # REDIS_PORT: 6379
      UPDATE_GRACE_PERIOD_SECONDS: 5s
      DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS: 5s
      # REDIS_KEY_PREFIX_DEPLOYMENT_LAST_ACTION: deploymentid:last_action
      # REDIS_KEY_PREFIX_DEPLOYMENT_API_METRIC: deploymentid:minio-metrics
    depends_on:
      - redis

  redis:
    container_name: cwm-redis-metrics
    image: redis:6
    ports:
      - "6379:6379"
