version: '3.4'

services:

  logger:
    container_name: cwm-worker-logger
    image: cwm-worker-logger
    build: .
    ports:
      - "8500:8500"
    # volumes:
    #   - "./config/:/fluentd/etc/"
    environment:
      REDIS_HOST: "redis"
      LOG_LEVEL: "debug"
      UPDATE_GRACE_PERIOD_SECONDS: 5s
      DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS: 5s
    command: -c "/fluentd/etc/fluent.conf"
    depends_on:
      - redis

  redis:
    container_name: cwm-redis-metrics
    image: redis:6
    ports:
      - "6379:6379"
