version: '3.4'

services:

  logger:
    image: cwm-worker-logger
    build: .
    ports:
      - "8500:8500"
    environment:
      CWM_WORKER_LOGGER_CONFIG_FILE: "/opt/cwm-worker-logger-config/config.json"
    volumes:
      - "./.config:/opt/cwm-worker-logger-config"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
